version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: coucoudas
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: coucoudas123
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  server:
    container_name: server
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
