server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    username: root
    password: coucoudas123
    url: jdbc:mysql://localhost:3306/coucoudas?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&tinyInt1isBit=false&rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        ## bulk insert 옵션 ##
        # 정렬 옵션
        order_inserts: true
        order_updates: true
        # 한번에 나가는 배치 개수 -> 100개의 insert를 1개로 보낸다.
        jdbc:
          batch_size: 10
          time_zone: Asia/Seoul
        show_sql: true
        format_sql: true   # sql 출력문의 모양을 잡아준다.
        use_sql_comments: true   # 콘솔에 표시되는 쿼리문 위에 어떤 실행을 하려는지 힌트 표시, 주석 표시
    defer-datasource-initialization: true

  sql:
    init:
      mode: always